### ISSUE TITLE
API version error. 

### ISSUE THREAD

**Issue by ziad-abdo** [cronitorio/cronitor-ruby#13]
I recently encountered an error when initializing cronitor passing in options including a :name key. 
```
Cronitor::Error: name: name must be unique
    from (irb):9:in `new'
    from (irb):9
```

And I was really puzzled, because the monitor had definitely been created already, but the related background worker had been issuing run and complete pings for months. 

I manually ran the code in the `exists?` method https://github.com/evertrue/cronitor/blob/master/lib/cronitor.rb#L50. To see what was in the response and found:

```
irb(main):057:0> response = http.request request
=> #<Net::HTTPBadRequest 400 BAD REQUEST readbody=true>
irb(main):059:0> response.body
=> "\"Please use /v3/monitors for this monitor type\""
```

Its not totally clear to me what changed about the monitor that would change its type-- nor how I could have been aware of it. Is there a plan to upgrade the library to use `/v3/` ? Is there some documentation where I could learn what monitor types are supported by v1?

**Comment by jeffbyrnes** [comment]
Hi @ziad-abdo, thanks for reaching out. The last commit to this project was Nov 30, 2017, af8ef3f, so I’m not surprised if Cronitor has added a new API version, and deprecated some or all of their v1 API.

Their API is self-documenting, and if I head over to https://cronitor.io/v1/monitors after logging in, I can see a valid response.

Your code above doesn’t include the value of `request`, so I’m unable to replicate your query. 

That said, if you want to try it out manually, but get a valid response per their error, I would manually run this code:

```ruby
name = 'Your Monitor Name'

uri = URI.parse "https://cronitor.io/v3/monitors/#{URI.escape name}"

http = Net::HTTP.new uri.host, uri.port
http.use_ssl = uri.scheme == 'https'

request = Net::HTTP::Get.new uri.path, { 'Accept' => 'application/json' }
request.basic_auth ENV['CRONITOR_TOKEN'], nil

response = http.request request

return false unless response.is_a? Net::HTTPSuccess

JSON.parse response.body
```

and see what that turns up. I’ve condensed the library code there into something that can be run a bit more easily using `irb` or `pry`, though you’ll need your API key set to the `CRONITOR_TOKEN` env var like usual.

I don’t have any Cronitor monitors set up at the moment, but if you let me know what kind of monitor you’ve created, I could attempt to re-create your situation and see what I see.

**Comment by jeffbyrnes** [comment]
Ah, took a little clicking around, but I discovered that they’ve documented changes from v1 to v3 in their [Monitor API docs](https://cronitor.io/docs/monitor-api).

**Comment by ziad-abdo** [comment]
Yeah, so I am able to successfully make a GET request when I use v3, but I was a little concerned with changing it to v3 without some confirmation that it wouldn't have some other unexpected issue/behavior. Fwiw, whatever we changed on the monitor in the cronitor UI clearly affected the type  of monitor it was somehow. But I was not really given a warning or anything.

The type that it is, is `"type"=>"cron"`That might help you debug it? I'd be happy to make a PR that makes the api version optional if that seems appropriate.

**Comment by jeffbyrnes** [comment]
Yeah, that is probably enough to go on. Sorry for the slow reply; I’m not using Cronitor in my current job, so having to find time on-the-side to check this out 😄

**Comment by ziad-abdo** [comment]
No worries, and no rush @jeffbyrnes, for the time being we’re using the work around and it seems successful.

**Comment by jeffbyrnes** [comment]
Hey there, wanted to let you know I haven’t forgotten about this, and am hoping to clean it up over my holiday break! Work’s been busy busy.

**Comment by cronitorio** [comment]
@jeffbyrnes just wanted to say THANK YOU for continuing to maintain this, and for putting out the 3.0.0 release 🎉 🎉 🎉

**Comment by jeffbyrnes** [comment]
@cronitorio you're welcome! Thanks for continuing to provide an excellent service.

**Comment by cronitorio** [comment]
@jeffbyrnes thanks! 

We'd like to start taking responsibility for providing Cronitor supported open-source client libraries. Our Github account would host the clients and take a more active roll in the development of all clients. We'd like to start with Ruby, Python, Java, PHP, Elixir, Javascript, and Bash - https://cronitor.io/docs/open-source-libraries - as well as open-source our own Go client.

Our goal is to help standardize documentation, nomenclature, feature development, and testing, as well as keeping the APIs current, and, in some cases, adding or consolidating Ping and Monitor APIs.

Ideally, we'd like to transfer ownership of existing libraries for continuity.  We'll clearly note original client authors on the README. And any maintainers who would like to continue contributing to the projects will continue to have maintainer access. Would you be interested in helping us do this for the Ruby library?

**Comment by jeffbyrnes** [comment]
@cronitorio I would _love_ to participate. Happy to continue contributing, as well.

That said, my employer two jobs ago is technically the owner of this repo. Lets loop in @haizhou, who still works there, and see if he can get the ball rolling on transferring ownership to y’all so this can become better supported.

**Comment by haizhou** [comment]
@jeffbyrnes @cronitorio Thanks for the continuous support on this library! I attempted an ownership transfer of this repo just moments ago, but it appears that I can only transfer the ownership to an organization where I have the permission to create a repo. What would be the best way to proceed? Possible for me to transfer the ownership to an individual github user?

**Comment by aflanagan** [comment]
@haizhou thanks so much! I just sent you an invite to the Cronitorio organization. Once you accept that you should be able to transfer over the repo.

**Comment by aflanagan** [comment]
Thanks @haizhou! In terms of updating rubygems, is it possible to give the user cronitorio permissions to publish this gem?

**Comment by jeffbyrnes** [comment]
@aflanagan I can take care of that/

**Comment by jeffbyrnes** [comment]
@aflanagan all set!

**Comment by aflanagan** [comment]
Thanks @jeffbyrnes!
