### ISSUE TITLE
Where should we put Cronitor#job & yaml file

### ISSUE THREAD

**Issue by akashkinwad** [cronitorio/cronitor-ruby#21]
I am trying to use cronitor for my rails project.
But after reading documentation Im not able to set it up.

Where should we put Cronitor#job ? it should be inside initializer ?

Can some one please help me to understand the process of using this gem.
Its very difficult to understand from the current documentation.

**Comment by jeffbyrnes** [comment]
That all depends on what your Rails project is meant to do.

It’s been a while, but based on what I recall, I’ll make a few assumptions:

* Your Rails project is a website
* You have one or more jobs that run as part of your website’s functionality
* You want to monitor this job or jobs via Cronitor

If the above is correct, some thoughts on what I’d do.

I would choose to set the API key, via either `CRONITOR_API_KEY` env var or `Cronitor.api_key` method call, as part of your initializer. This should ensure that every call to the gem has your API key available.

Anywhere in your Rails app library code that you’re calling something you want to report on via Cronitor, wrap it like so:

```ruby
Cronitor.job 'your-job-name' do
  # whatever code is necessary for your job to run
end
```

As the README says:

> The `Cronitor#job` helper will send telemetry events before calling your block and after it exits. If your block raises an exception a `fail` event will be sent (and the exception re-raised).

So the important part with your own code is to ensure that it raises an exception if it does not work as intended, and the Cronitor gem will report the run as failed to the Cronitor service.

**Comment by akashkinwad** [comment]
Thank you @jeffbyrnes for clarification.
